x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
print(x-y)
print(x*y)
print("Subtraction of two numbers is", f'{x-y}')
print("Multiplication of two numbers is",f'{x*y}')